### PR TITLE
UI improvement in cards section

### PR DESCRIPTION
**Pull request by om453**
Changes done !

Final Output

https://github.com/user-attachments/assets/d61dc6c5-d173-4511-afa7-a5abf58664b7

### CODE REVIEW

**Comment by M-ayank2005** [comment]
This yellow background is not there behind cards.
You are working on previous commits.

**Comment by om453** [comment]
could you check it now

**Comment by M-ayank2005** [comment]
@om453  firstly look at the deployment check failed

**Comment by om453** [comment]
@M-ayank2005  ok let me check

**Pull request closed without merging**
